"""add_video_metadata_fields

Revision ID: a1cbb5116dde
Revises: 94ce106c793c
Create Date: 2026-03-22 18:29:36.443301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cbb5116dde'
down_revision: Union[str, None] = '94ce106c793c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('channel_name', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('upload_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'upload_date')
    op.drop_column('videos', 'view_count')
    op.drop_column('videos', 'channel_name')
    # ### end Alembic commands ###
